services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Blueways\BwPlaceholderImages\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Form'

  querybuilder.metadata:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'sys_file_metadata'

  Blueways\BwPlaceholderImages\Utility\TriangularUtility:
    public: true
    arguments:
      $metadataQueryBuilder: '@querybuilder.metadata'

  Blueways\BwPlaceholderImages\Command\RequestTriangularImageCommand:
    tags:
      - name: 'console.command'
        command: 'placeholder:requestTriangularImage'
        description: 'Starts the routine of processing and downloading triangular images'
        # not required, defaults to false
        hidden: false

